services:
  jellyfin:
    image: "${IMAGE}"
    container_name: "jellyfin"
    restart: "always"
    networks:
      - "reverse-proxy"
    expose:
      - "8096"
    volumes:
      - "./config:/config"
      - "./cache:/cache"
      - "media:/media"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=web, websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.home.tastic`)"
      - "diun.enable=true"
      - "diun.include_tags=^10\\.\\d+\\.\\d+$"
      - "homepage.group=Media & Entertainment"
      - "homepage.name=Jellyfin"
      - "homepage.icon=jellyfin.png"
      - "homepage.href=https://jellyfin.home.tastic"
      - "homepage.description=Media Streaming"
      - "homepage.widget.type=jellyfin"
      - "homepage.widget.url=https://jellyfin.home.tastic"
      - "homepage.widget.key=${JELLYFIN_API_KEY}"
      - "homepage.widget.enableBlocks=true"
      - "homepage.widget.enableNowPlaying=false"

volumes:
  media:
    driver_opts:
      type: cifs
      o: "noserverino,username=${MEDIA_USERNAME},password=${MEDIA_PASSWORD},iocharset=utf8"
      device: "//${MEDIA_NAS}/${SHARE_NAME}"

networks:
  reverse-proxy:
    external: true

